title: Ana Sol√≥rzano
url: "http://anaveroneze.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "http://anaveroneze.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "About"
#    link: "/researcher/"
 - name: "Contact"
   link: "contact"
